pull_request_rules:
  - name: Merge non-breaking dependencies
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "title~=.+ from (?P<major>\\d+).\\d+.\\d+.* to
        (?P=major).\\d.\\d.*"
    actions:
      merge:
        method: squash
