name: Build Documentation
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build and deploy documentation
        uses: nearlysplat/action-docs@development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
