name: Build Documentation
on:
  push:
    branches:
      - main
      - rewrite
    tags:
      - '*'
    paths:
      -  typings/**/*.d.ts
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16


      - name: Use dependency cache
        uses: actions/cache@v3
        with:
          path: | 
            ~/.pnpm-store
            node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]


      - name: Build and deploy documentation
        uses: splatterxl/action-docs@development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
