name: Lint Source
on:
  push:
    paths:
      - package.json
      - pnpm-lock.yaml 
      - "**/*.ts"
      - "**/*.js"
  pull_request:
jobs:
  test:
    name: Lint Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16 

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]


      - name: Use dependency cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml')

      - name: Use build cache
        uses: actions/cache@v3
        with:
          path: dist
          key: build-${{ runner.os }}-${{ hashFiles('src/**/*.ts') }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Build project
        run: tsc -p tsconfig.json

      - name: Run tests
        run: npm run lint
