name: Draft release
on:
  push:
    branches:
      - main
jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      APP: fuwa
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Bump version and push tag
        uses: darioblanco/release-wizard@main
        id: bump_version
        with:
          taskPrefix: ${{ env.APP }}@
          token: ${{ github.token }}
          templatePath: RELEASE_DRAFT/default.md
      - name: Create Release
        uses: darioblanco/release-wizard@main
        with:
          app: ${{ env.APP }}
          releaseName: ${{ env.APP }} ${{ steps.bump_version.outputs.version }}
          releaseTag: ${{ steps.bump_version.outputs.tag }}
          templatePath: RELEASE_DRAFT/default.md
          token: ${{ github.token }}
