name: Update pnpm lockfile 
on: 
  push:
    paths:
      - package.json
    branches:
      - rewrite
      - main

jobs:
  update-lockfile:
    name: Update pnpm lockfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16 
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.2
          run_install: |
            - recursive: true
              args: [--strict-peer-dependencies]
      - name: Commit changed lockfile 
        run: |
          git add pnpm-lock.yaml || true
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git commit -m "chore(deps): update pnpm lockfile" || true
          git pull --rebase
          git push